# Generated by Django 2.2.24 on 2021-08-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityFake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('temp', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
